# Use Node.js image
FROM node:20-alpine

# Set working directory
WORKDIR /usr/src/app

# Install dependencies
# Copy package.json and package-lock.json first to leverage Docker cache
COPY package*.json ./

RUN npm install

# Copy source code into the container
COPY . .

# Expose the port your application runs on (default for NestJS is 3000)
EXPOSE 3000

# Start the application in development mode with hot-reloading
CMD ["npm", "run", "start:dev"]
